import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

const deploymentProfile = process.env.VITE_DEPLOYMENT_PROFILE || 'local'
if (!['local', 'hosted'].includes(deploymentProfile)) {
  throw new Error(`Unsupported VITE_DEPLOYMENT_PROFILE: ${deploymentProfile}`)
}

// Vite configuration for the React frontend.
// Original scaffold generated by Vite.
// Additional server settings added for Docker container networking.

export default defineConfig({
  plugins: [react()],

  resolve: {
    alias: {
      '@edge-app': deploymentProfile === 'hosted' ? '/src/HostedApp.jsx' : '/src/App.jsx',
    },
  },

  // mqtt.js references the Node global `global` in its browser build; map it to
  // globalThis so the MQTT-over-WebSockets client works in the browser.
  define: {
    global: 'globalThis',
  },

  build: {
    rollupOptions: {
      input: {
        app: 'index.html',
        bleLab: 'ble-lab.html',
      },
    },
  },

  server: {
    // Allow the Vite dev server to listen on all container interfaces.
    // Without this, nginx and other Docker containers cannot reach Vite.
    host: '0.0.0.0',

    // Explicitly run Vite on port 5173.
    // nginx will proxy frontend traffic to this port.
    port: 5173,

    allowedHosts: ['react', 'localhost']
  }
})
