// Builds the browser UI and keeps local API requests on a loopback-only proxy.
// Production uses Nginx for the same /api routing instead of this development server.
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// Vite configuration for the React frontend.
// Original scaffold generated by Vite.
// Additional server settings added for Docker container networking.

export default defineConfig({
  plugins: [react()],

  // mqtt.js references the Node global `global` in its browser build; map it to
  // globalThis so the MQTT-over-WebSockets client works in the browser.
  define: {
    global: 'globalThis',
  },

  server: {
    // Local development is loopback-only. Pass --host explicitly when testing
    // from another device on a trusted network.
    host: '127.0.0.1',

    // Explicitly run Vite on port 5173.
    // nginx will proxy frontend traffic to this port.
    port: 5173,

    allowedHosts: ['react', 'localhost'],

    // Keep browser requests same-origin during local development. Production
    // uses Nginx for the same /api route.
    proxy: {
      '/api': {
        target: 'http://127.0.0.1:8000',
        changeOrigin: true,
        timeout: 10_000,
        proxyTimeout: 10_000,
      },
    },
  }
})
