# Generated by Django 5.1.2 on 2026-07-07 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nfc_tag_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=255, unique=True)),
                ('rack_number', models.IntegerField(blank=True, null=True)),
                ('mount_type', models.CharField(choices=[('bar', 'Bar'), ('waist', 'Waist'), ('wrist', 'Wrist')], default='bar', max_length=10)),
                ('firmware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RackScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('rack_number', models.IntegerField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=255)),
                ('target_sets', models.IntegerField()),
                ('target_reps', models.IntegerField()),
                ('target_weight_lbs', models.FloatField()),
                ('velocity_zone_min', models.FloatField()),
                ('velocity_zone_max', models.FloatField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='event_handler.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('athletes', models.ManyToManyField(related_name='sessions', to='event_handler.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=255)),
                ('set_number', models.IntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('reps_completed', models.IntegerField(default=0)),
                ('avg_velocity', models.FloatField(blank=True, null=True)),
                ('peak_velocity', models.FloatField(blank=True, null=True)),
                ('is_false_set', models.BooleanField(default=False)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='event_handler.athlete')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sets', to='event_handler.node')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='event_handler.session')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_number', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('mean_velocity', models.FloatField()),
                ('peak_velocity', models.FloatField()),
                ('duration_ms', models.IntegerField()),
                ('velocity_color', models.CharField(max_length=16)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reps', to='event_handler.set')),
            ],
            options={
                'ordering': ['rep_number'],
            },
        ),
    ]
