# Generated by Django 5.1.2 on 2026-07-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='weight_lbs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
