# Generated by Django 5.1.2 on 2026-07-17 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0002_set_weight_lbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteReferenceMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=255)),
                ('reference_weight_lbs', models.FloatField()),
                ('rep_basis', models.IntegerField(default=1)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('estimated', 'Estimated')], default='manual', max_length=16)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_maxes', to='event_handler.athlete')),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_reference_maxes', to='event_handler.session')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['athlete', 'exercise', '-recorded_at'], name='event_handl_athlete_943cc6_idx')],
            },
        ),
    ]
