# Generated by Django 5.1.2 on 2026-07-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0005_link_models_to_exercise_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='is_makeup',
            field=models.BooleanField(default=False),
        ),
    ]
