# Generated by Django 5.1.2 on 2026-07-20 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0006_set_is_makeup'),
    ]

    operations = [
        migrations.CreateModel(
            name='RackCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_number', models.IntegerField()),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='event_handler.athlete')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='event_handler.session')),
            ],
            options={
                'ordering': ['-checked_in_at'],
                'indexes': [models.Index(fields=['session', 'athlete', '-checked_in_at'], name='checkin_session_athlete_idx')],
            },
        ),
    ]
