# Generated by Django 5.1.2 on 2026-07-24 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0007_rackcheckin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reason', models.CharField(max_length=32)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('publish_attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('is_simulated', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='is_simulated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='allowed_exercises',
            field=models.ManyToManyField(blank=True, related_name='allowed_on_nodes', to='event_handler.exercise'),
        ),
        migrations.AddField(
            model_name='node',
            name='is_simulated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='is_simulated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='set',
            name='is_coach_adjustment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='set',
            name='is_simulated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TrainingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration_weeks', models.IntegerField(blank=True, null=True)),
                ('cadence_days_of_week', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_blocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingBlockWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField()),
                ('training_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='event_handler.trainingblock')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='TrainingBlockExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('target_percent', models.FloatField()),
                ('velocity_zone_min', models.FloatField(blank=True, null=True)),
                ('velocity_zone_max', models.FloatField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_block_exercises', to='event_handler.exercise')),
                ('training_block_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='event_handler.trainingblockworkout')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='training_groups',
            field=models.ManyToManyField(blank=True, related_name='athletes', to='event_handler.traininggroup'),
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='event_handler.trainingblock')),
                ('training_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='event_handler.traininggroup')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('target_percent', models.FloatField()),
                ('velocity_zone_min', models.FloatField(blank=True, null=True)),
                ('velocity_zone_max', models.FloatField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_program_exercises', to='event_handler.exercise')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='AthleteWorkoutExerciseOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_percent', models.FloatField(blank=True, null=True)),
                ('sets', models.PositiveIntegerField(blank=True, null=True)),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercise_overrides', to='event_handler.athlete')),
                ('training_program_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_overrides', to='event_handler.trainingprogramexercise')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgramWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField()),
                ('training_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='event_handler.trainingprogram')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='trainingprogramexercise',
            name='training_program_workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='event_handler.trainingprogramworkout'),
        ),
        migrations.CreateModel(
            name='SessionParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='event_handler.session')),
                ('training_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_participations', to='event_handler.trainingprogram')),
                ('training_program_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_participations', to='event_handler.trainingprogramworkout')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trainingblockworkout',
            constraint=models.UniqueConstraint(fields=('training_block', 'position'), name='block_workout_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='trainingblockexercise',
            constraint=models.UniqueConstraint(fields=('training_block_workout', 'position'), name='block_exercise_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='athleteworkoutexerciseoverride',
            constraint=models.UniqueConstraint(fields=('athlete', 'training_program_exercise'), name='athlete_override_unique_per_exercise'),
        ),
        migrations.AddConstraint(
            model_name='athleteworkoutexerciseoverride',
            constraint=models.CheckConstraint(condition=models.Q(('target_percent__isnull', False), ('sets__isnull', False), ('reps__isnull', False), _connector='OR'), name='athlete_override_at_least_one_field'),
        ),
        migrations.AddConstraint(
            model_name='trainingprogramworkout',
            constraint=models.UniqueConstraint(fields=('training_program', 'position'), name='program_workout_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='trainingprogramexercise',
            constraint=models.UniqueConstraint(fields=('training_program_workout', 'position'), name='program_exercise_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='sessionparticipation',
            constraint=models.UniqueConstraint(fields=('session', 'training_program'), name='session_participation_unique'),
        ),
    ]
