# Generated by Django 5.1.2 on 2026-07-25 06:23

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0009_seed_exercise_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='daily_report', to='event_handler.session')),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
                'indexes': [models.Index(fields=['-generated_at', '-id'], name='daily_report_newest_idx'), django.contrib.postgres.indexes.GinIndex(models.Func(models.F('snapshot'), models.Value('$.athletes[*].athlete.id'), function='jsonb_path_query_array'), name='daily_report_athlete_ids_gin')],
                'constraints': [models.CheckConstraint(condition=models.Q(('schema_version__gte', 1)), name='daily_report_positive_schema_version')],
            },
        ),
    ]
