# Generated by Django 5.1.2 on 2026-07-28 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0010_daily_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sets', to='event_handler.session'),
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
