# Generated by Django 5.1.2 on 2026-07-29 19:39
#
# P11 step 2 — labels for finding things in the shared block catalog.
#
# Additive and safe on an existing database: a new table plus a join table.
# Nothing is backfilled and nothing is required, so every block that already
# exists simply has no categories until a coach adds some. There is no data
# migration here because there is no old field to read one out of.
#
# Deliberately a NEW table rather than reusing `Tag` — Tag's names are movement
# labels on Exercise and are globally unique, so sharing it would make one word
# mean two things. See the BlockCategory docstring.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0013_trainingblock_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'block categories',
            },
        ),
        migrations.AddField(
            model_name='trainingblock',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='blocks', to='event_handler.blockcategory'),
        ),
    ]
