# Generated by Django 5.1.2 on 2026-08-11 03:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0024_organization_local_nfc_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiThrottleBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=48)),
                ('key_digest', models.CharField(max_length=64)),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='api_throttle_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'key_digest', 'window_start'), name='api_throttle_window_unique')],
            },
        ),
        migrations.CreateModel(
            name='BrowserEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(default='rack', max_length=16)),
                ('display_name', models.CharField(max_length=80)),
                ('endpoint_revision', models.PositiveBigIntegerField(default=1)),
                ('state', models.CharField(choices=[('active', 'Active'), ('unpaired', 'Unpaired'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('helper_status_cursor', models.PositiveBigIntegerField(default=1)),
                ('helper_status', models.CharField(blank=True, max_length=32, null=True)),
                ('helper_status_at', models.DateTimeField(blank=True, null=True)),
                ('helper_status_boot_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='browser_endpoints', to='event_handler.organization')),
                ('training_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='browser_endpoints', to='event_handler.traininggroup')),
            ],
        ),
        migrations.CreateModel(
            name='RackHelperInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(default='pending_activation', max_length=24)),
                ('platform', models.CharField(max_length=16)),
                ('contract_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activation_expires_at', models.DateTimeField()),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_request_id', models.UUIDField(blank=True, null=True)),
                ('last_status_boot_id', models.UUIDField(blank=True, null=True)),
                ('last_status_value', models.CharField(blank=True, max_length=32)),
                ('last_status_response', models.JSONField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='helper_installations', to='event_handler.browserendpoint')),
            ],
        ),
        migrations.CreateModel(
            name='RackHelperLaunchIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('consumer_boot_id', models.UUIDField(blank=True, null=True)),
                ('consume_request_id', models.UUIDField(blank=True, null=True)),
                ('ack_cursor', models.PositiveBigIntegerField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='launch_intents', to='event_handler.browserendpoint')),
                ('target_installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='launch_intents', to='event_handler.rackhelperinstallation')),
            ],
        ),
        migrations.AddField(
            model_name='browserendpoint',
            name='last_launch_intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_for_endpoints', to='event_handler.rackhelperlaunchintent'),
        ),
        migrations.CreateModel(
            name='RackHelperPairing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_digest', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('bootstrap_digest', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('proposed_credential_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('proposed_credential_digest', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('platform', models.CharField(blank=True, max_length=16)),
                ('contract_version', models.PositiveIntegerField(blank=True, null=True)),
                ('confirmation_phrase_digest', models.CharField(blank=True, max_length=64)),
                ('confirmation_phrase', models.JSONField(blank=True, null=True)),
                ('server_nonce', models.BinaryField(max_length=32)),
                ('state', models.CharField(default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activation_request_id', models.UUIDField(blank=True, null=True)),
                ('activation_response', models.JSONField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='helper_pairings', to='event_handler.browserendpoint')),
            ],
        ),
        migrations.AddField(
            model_name='rackhelperinstallation',
            name='pairing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='installation', to='event_handler.rackhelperpairing'),
        ),
        migrations.CreateModel(
            name='EndpointCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_digest', models.CharField(max_length=64, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='event_handler.browserendpoint')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('endpoint',), name='one_active_endpoint_credential'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='endpoint_credential_version_positive'), models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', False), ('state', 'revoked')), models.Q(('revoked_at__isnull', True), ('state', 'active')), _connector='OR'), name='endpoint_credential_revocation_state')],
            },
        ),
        migrations.CreateModel(
            name='EndpointPairing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_digest', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('bootstrap_digest', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('credential_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('state', models.CharField(default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='endpoint_pairings', to='event_handler.browserendpoint')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('claimed_at__isnull', True), ('delivered_at__isnull', True), ('endpoint__isnull', True), ('state', 'pending')), models.Q(('claimed_at__isnull', False), ('delivered_at__isnull', True), ('endpoint__isnull', False), ('state', 'claimed')), models.Q(('claimed_at__isnull', False), ('delivered_at__isnull', False), ('endpoint__isnull', False), ('state', 'delivered')), models.Q(('delivered_at__isnull', True), ('state__in', ['expired', 'cancelled'])), _connector='OR'), name='endpoint_pairing_state_shape')],
            },
        ),
        migrations.CreateModel(
            name='RackHelperCredential',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('secret_digest', models.CharField(max_length=64, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(default='pending', max_length=16)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='event_handler.rackhelperinstallation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('state__in', ['pending', 'active'])), fields=('installation',), name='one_current_helper_credential'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='helper_credential_version_positive')],
            },
        ),
        migrations.CreateModel(
            name='RackHelperLaunchConsumeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_request_id', models.UUIDField()),
                ('helper_boot_id', models.UUIDField()),
                ('intent_id', models.UUIDField()),
                ('acknowledged_at', models.DateTimeField()),
                ('ack_cursor', models.PositiveBigIntegerField()),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='launch_consume_receipts', to='event_handler.rackhelperinstallation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('installation', 'consume_request_id'), name='helper_consume_receipt_unique'), models.CheckConstraint(condition=models.Q(('ack_cursor__gte', 1)), name='consume_receipt_cursor_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='rackhelperlaunchintent',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('endpoint',), name='one_pending_launch_intent'),
        ),
        migrations.AddConstraint(
            model_name='rackhelperlaunchintent',
            constraint=models.UniqueConstraint(condition=models.Q(('consume_request_id__isnull', False)), fields=('target_installation', 'consume_request_id'), name='launch_consume_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='rackhelperlaunchintent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ack_cursor__isnull', False), ('consume_request_id__isnull', False), ('consumed_at__isnull', False), ('consumer_boot_id__isnull', False), ('state', 'consumed'), ('target_installation__isnull', False)), models.Q(('ack_cursor__isnull', True), ('consume_request_id__isnull', True), ('consumed_at__isnull', True), ('consumer_boot_id__isnull', True), ('state__in', ['pending', 'superseded', 'expired', 'cancelled'])), _connector='OR'), name='launch_intent_consume_shape'),
        ),
        migrations.AddConstraint(
            model_name='browserendpoint',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'rack')), name='browser_endpoint_rack_kind'),
        ),
        migrations.AddConstraint(
            model_name='browserendpoint',
            constraint=models.CheckConstraint(condition=models.Q(('endpoint_revision__gte', 1)), name='browser_endpoint_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='browserendpoint',
            constraint=models.CheckConstraint(condition=models.Q(('helper_status_cursor__gte', 1)), name='browser_endpoint_cursor_positive'),
        ),
        migrations.AddConstraint(
            model_name='browserendpoint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', False), ('state', 'revoked')), models.Q(('revoked_at__isnull', True), ('state__in', ['active', 'unpaired'])), _connector='OR'), name='browser_endpoint_revocation_state'),
        ),
        migrations.AddConstraint(
            model_name='rackhelperpairing',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['pending', 'claimed', 'confirmed'])), fields=('endpoint',), name='one_current_helper_pairing'),
        ),
        migrations.AddConstraint(
            model_name='rackhelperinstallation',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['pending_activation', 'active'])), fields=('endpoint',), name='one_current_helper_installation'),
        ),
    ]
