# Generated by Django 5.1.2 on 2026-08-11 03:54

import datetime
import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0025_apithrottlebucket_browserendpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointpairing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='rackhelperlaunchintent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='rackhelperpairing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddConstraint(
            model_name='endpointpairing',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at', django.db.models.expressions.CombinedExpression(models.F('created_at'), '+', models.Value(datetime.timedelta(seconds=300))))), name='endpoint_pairing_five_minute_expiry'),
        ),
        migrations.AddConstraint(
            model_name='rackhelperlaunchintent',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at', django.db.models.expressions.CombinedExpression(models.F('created_at'), '+', models.Value(datetime.timedelta(seconds=300))))), name='launch_intent_five_minute_expiry'),
        ),
        migrations.AddConstraint(
            model_name='rackhelperpairing',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at', django.db.models.expressions.CombinedExpression(models.F('created_at'), '+', models.Value(datetime.timedelta(seconds=300))))), name='helper_pairing_five_minute_expiry'),
        ),
    ]
