# Generated by Django 5.1.2 on 2026-09-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0026_assign_existing_coaches'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttemptWindow',
            fields=[
                ('account_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('failures', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
    ]
