# Generated by Django 5.1.2 on 2026-08-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0026_alter_endpointpairing_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rackhelpercredential',
            name='secret_digest',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='browserendpoint',
            constraint=models.CheckConstraint(condition=models.Q(('helper_status__isnull', True), ('helper_status__in', ['launching', 'no_sensor', 'scanning', 'verifying', 'ready', 'active_online', 'active_offline', 'stopping', 'draining', 'released', 'credential_revoked', 'authentication_blocked', 'sensor_reconnecting', 'queue_full', 'queue_corrupt', 'keychain_unavailable', 'update_required', 'queue_unsafe', 'queue_read_only', 'queue_write_failed', 'endpoint_reassigned', 'recovery_required']), _connector='OR'), name='browser_endpoint_helper_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='rackhelpercredential',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activated_at__isnull', True), ('revoked_at__isnull', True), ('secret_digest__isnull', False), ('state', 'pending')), models.Q(('activated_at__isnull', False), ('revoked_at__isnull', True), ('secret_digest__isnull', False), ('state', 'active')), models.Q(('revoked_at__isnull', False), ('state', 'revoked')), _connector='OR'), name='helper_credential_state_shape'),
        ),
        migrations.AddConstraint(
            model_name='rackhelperinstallation',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['pending_activation', 'active', 'expired', 'cancelled', 'revoked'])), name='helper_installation_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='rackhelperinstallation',
            constraint=models.CheckConstraint(condition=models.Q(('platform__in', ['linux_x64', 'windows_x64'])), name='helper_installation_platform_valid'),
        ),
        migrations.AddConstraint(
            model_name='rackhelperlaunchintent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', True), ('state', 'superseded'), ('superseded_at__isnull', False)), models.Q(('cancelled_at__isnull', False), ('state', 'cancelled'), ('superseded_at__isnull', True)), models.Q(('cancelled_at__isnull', True), ('state__in', ['pending', 'consumed', 'expired']), ('superseded_at__isnull', True)), _connector='OR'), name='launch_intent_terminal_timestamp_shape'),
        ),
        migrations.AddConstraint(
            model_name='rackhelperpairing',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['pending', 'claimed', 'confirmed', 'activated', 'expired', 'cancelled'])), name='helper_pairing_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='rackhelperpairing',
            constraint=models.CheckConstraint(condition=models.Q(('platform', ''), ('platform__in', ['linux_x64', 'windows_x64']), _connector='OR'), name='helper_pairing_platform_valid'),
        ),
    ]
