# Generated by Django 5.1.2 on 2026-08-11 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0027_alter_rackhelpercredential_secret_digest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rackhelperpairing',
            name='confirmation_phrase',
        ),
    ]
