#!/usr/bin/env python3
"""Keep the route list in the docs matching urls.py.

The sibling of refresh-schema.py, and it works the same way. journal/apis.md lists
every endpoint the server has. That list has to come from the code, or the first
route somebody adds goes undocumented and the page slowly becomes fiction.

WHAT IS GENERATED vs WHAT IS YOURS
Each group gets ONE table — route, methods, access, what it does, handler — and that
table is what sits between the markers and gets replaced on every run:

    <!-- routes:the-room:start -->
    | Route | Methods | Access | What it does | Handler |
    <!-- routes:the-room:end -->

The descriptions come from each view's docstring, so a route is described in exactly
one place: the code. To reword one, edit the docstring.

Everything OUTSIDE the markers is yours and is never touched — the group blurb, and
any decisions you write beneath a table.

USAGE
    ./refresh-routes.py            update the facts, keep all prose
    ./refresh-routes.py --check    change nothing, exit 1 if the page has drifted
    ./refresh-routes.py --rebuild  regenerate the whole section from scratch
                                   (DESTRUCTIVE — discards prose; first-time setup only)

A new route appears in its group's table automatically. A whole new group is appended
with its table. A group that empties out keeps its section, because whatever was
written under it may still be worth reading.
"""
import argparse
import ast
import re
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parent
REPO = DOCS.parent
APP = REPO / "django" / "event_handler"
URLS = APP / "urls.py"
VIEW_MODULES = ["views.py", "health.py", "system_status.py", "wifi_config.py"]
PAGE = DOCS / "journal" / "apis.md"

SECTION_START = "<!-- ROUTES SECTION START — generated by docs/refresh-routes.py -->"
SECTION_END = "<!-- ROUTES SECTION END -->"

# Which group each route falls into, matched on the start of its path. Order matters:
# the first prefix that matches wins, and it is also the order groups appear.
#
# ⚠️ ADD NEW PREFIXES HERE. A route matching nothing still gets documented — it lands
# under "Unsorted" — but it belongs in a real group.
GROUPS = [
    ("System",
     "Health, and the settings an operator changes before a real gym uses the box.",
     ("health/", "system/")),
    ("The room",
     "Rack screens, the sensors on them, and BLE enrolment.",
     ("racks/", "nodes/", "ble/")),
    ("People",
     "Athletes, the groups they train in, and the staff who run those groups.",
     ("athletes/", "training-groups/")),
    ("The movement catalog",
     "The shared vocabulary plans are written in.",
     ("exercises", "block-categories")),
    ("Templates",
     "Reusable training a coach designs once.",
     ("training-blocks/",)),
    ("Programs and the calendar",
     "A template placed in time, and the slots it generates.",
     ("training-programs/", "scheduled-sessions")),
    ("Running a training day",
     "The live session, and the room's current picture.",
     ("sessions/", "sessions", "room-state")),
    ("Performed work",
     "Sets, reps, prescriptions, maxes, and everything derived from them.",
     ("sets/", "prescriptions", "reference-maxes", "analytics/", "reports/")),
    ("Spreadsheet import",
     "Two routes for all three kinds of sheet.",
     ("imports/",)),
]
UNSORTED = "Unsorted"


def slug(path):
    """A marker-safe key for a route path. `racks/<int:n>/checkin/` -> racks-n-checkin"""
    s = re.sub(r"<[^:>]*:?([^>]*)>", r"\1", path)      # drop the converter, keep the name
    s = re.sub(r"[^a-zA-Z0-9]+", "-", s).strip("-")
    return s or "root"


def read_routes():
    """Every route in urls.py, joined to the view that handles it."""
    views = {}
    for mod in VIEW_MODULES:
        f = APP / mod
        if not f.exists():
            continue
        for node in ast.parse(f.read_text()).body:
            if not isinstance(node, ast.FunctionDef):
                continue
            methods, perm = None, ""
            for d in node.decorator_list:
                s = ast.unparse(d)
                if s.startswith("api_view"):
                    methods = ",".join(re.findall(r"'(\w+)'", s))
                if s.startswith("permission_classes"):
                    perm = s
            if methods:
                views[node.name] = {
                    "methods": methods,
                    "coach": "IsCoach" in perm,
                    "doc": " ".join((ast.get_docstring(node) or "").split()),
                }

    routes = []
    for m in re.finditer(r"path\(\s*'([^']*)'\s*,\s*(?:(\w+)\.)?(\w+)\s*,", URLS.read_text()):
        path, _, fn = m.groups()
        if fn in views:
            routes.append({"path": path, "fn": fn, "slug": slug(path), **views[fn]})
    return routes


def group_of(path):
    for i, (title, _, prefixes) in enumerate(GROUPS):
        if any(path.startswith(p) for p in prefixes):
            return i, title
    return len(GROUPS), UNSORTED


def generated_body(routes):
    """One table for a whole group — the ONLY thing a refresh overwrites.

    Fully generated, including the descriptions, which come from each view's
    docstring. To reword one, edit the docstring in the code: that keeps a single
    source of truth and means the docs improve as the code comments do. Anything you
    want to write yourself goes OUTSIDE the markers, below the table.
    """
    rows = ["| Route | Methods | Access | What it does | Handler |",
            "|---|---|---|---|---|"]
    for r in routes:
        access = "🔒 coach" if r["coach"] else "open"
        desc = r["doc"].split(". ")[0].rstrip(".") if r["doc"] else "—"
        desc = desc.replace("|", "\\|")
        rows.append(f"| `/api/{r['path']}` | `{r['methods']}` | {access} | {desc} | `{r['fn']}` |")
    return "\n".join(rows)


def group_slug(title):
    return re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")


def full_group(title, blurb, routes):
    """A complete section for a group nobody has written about yet."""
    n = len(routes)
    return (
        f"## {title}\n\n{blurb}\n\n"
        f":::::{{dropdown}} {n} route{'s' if n != 1 else ''}\n\n"
        f"<!-- routes:{group_slug(title)}:start -->\n"
        f"{generated_body(routes)}\n"
        f"<!-- routes:{group_slug(title)}:end -->\n\n"
        ":::::\n"
    )


def section_header():
    return f"""{SECTION_START}

<!-- Groups below are ## so this document keeps a single H1. -->

Every route the server has, grouped by what it touches. The summary is visible; the
detail is one click away. Generated from `urls.py` and the permission decorators, so
it matches what is actually wired up.
"""


def build_section(routes):
    """The whole section: one heading + one collapsible table per group."""
    out = [section_header()]
    for i, (title, blurb, _) in enumerate(GROUPS):
        rs = [r for r in routes if group_of(r["path"])[0] == i]
        if rs:
            out.append("\n" + full_group(title, blurb, rs))
    leftover = [r for r in routes if group_of(r["path"])[1] == UNSORTED]
    if leftover:
        out.append("\n" + full_group(
            UNSORTED,
            "Not filed into a group yet. Add a prefix to `GROUPS` in "
            "`docs/refresh-routes.py`.", leftover))
    out.append(f"\n{SECTION_END}\n")
    return "".join(out)


def refresh(text, routes):
    """Replace each group's table in place, leaving everything around it alone."""
    updated, added = [], []
    groups = list(GROUPS) + [(UNSORTED,
                              "Not filed into a group yet. Add a prefix to `GROUPS` in "
                              "`docs/refresh-routes.py`.", ())]

    for i, (title, blurb, _) in enumerate(groups):
        rs = ([r for r in routes if group_of(r["path"])[0] == i] if title != UNSORTED
              else [r for r in routes if group_of(r["path"])[1] == UNSORTED])
        gs = group_slug(title)
        pat = re.compile(rf"(<!-- routes:{gs}:start -->\n).*?(\n<!-- routes:{gs}:end -->)", re.S)

        if pat.search(text):
            if not rs:
                continue          # group emptied out; leave the section and its prose
            new = pat.sub(lambda mo: mo.group(1) + generated_body(rs) + mo.group(2), text)
            if new != text:
                updated.append(title)
            # keep the dropdown label's count honest
            new = re.sub(rf"(:::::\{{dropdown\}} )\d+ routes?(\n\n<!-- routes:{gs}:start)",
                         rf"\g<1>{len(rs)} route{'s' if len(rs) != 1 else ''}\g<2>", new)
            if new != text:
                text = new
        elif rs:
            block = "\n" + full_group(title, blurb, rs)
            text = text.replace(SECTION_END, block + SECTION_END)
            added.append(title)

    orphaned = [g for g in re.findall(r"<!-- routes:([\w-]+):start -->", text)
                if g not in {group_slug(t) for t, _, _ in groups}]
    return text, {"added": added, "updated": updated, "orphaned": orphaned}


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="change nothing; exit 1 if the page no longer matches urls.py")
    ap.add_argument("--rebuild", action="store_true",
                    help="regenerate the whole section, DISCARDING all prose")
    args = ap.parse_args()

    if not URLS.exists():
        sys.exit(f"urls.py not found at {URLS}")
    routes = read_routes()
    text = PAGE.read_text()

    if args.rebuild:
        if SECTION_START in text and SECTION_END in text:
            head = text.split(SECTION_START)[0]
            tail = text.split(SECTION_END, 1)[1]
        else:
            head, tail = text.rstrip() + "\n\n", "\n"
        PAGE.write_text(head + build_section(routes) + tail)
        print(f"rebuilt {len(routes)} routes (prose discarded)")
        return

    if SECTION_START not in text:
        sys.exit("No routes section found. Run with --rebuild once to create it.")

    new, report = refresh(text, routes)

    if args.check:
        if new != text:
            print("Route docs are out of date. Run: ./docs/refresh-routes.py")
            for k in ("added", "updated"):
                if report[k]:
                    print(f"  {k}: {', '.join(report[k])}")
            sys.exit(1)
        print(f"route docs up to date ({len(routes)} routes)")
        return

    if new != text:
        PAGE.write_text(new)

    if not report["added"] and not report["updated"]:
        print(f"no route changes ({len(routes)} routes)")
    else:
        if report["added"]:
            print(f"NEW routes documented (fill in the prose): {', '.join(report['added'])}")
        if report["updated"]:
            print(f"details refreshed: {', '.join(report['updated'])}")
    if report["orphaned"]:
        print(f"⚠ in the docs but no longer in urls.py: {', '.join(report['orphaned'])}")
        print("  left in place on purpose — the writing attached to them may still be useful")


if __name__ == "__main__":
    main()
