#!/usr/bin/env python3
"""Keep the table-by-table schema in the docs matching models.py.

WHAT THIS IS FOR
The database section of journal/database.md lists every table and its columns. That
list has to come from the code, or it quietly goes stale the first time somebody adds
a column — and a schema reference that is confidently wrong is worse than none at all.

THE PROBLEM IT HAS TO SOLVE
Each table also carries writing that only a person can produce: what the table is for,
why it exists, and the decisions attached to it. So this cannot simply regenerate the
whole section — that would delete everything anyone wrote.

So the generated parts are fenced off with HTML comment markers:

    <!-- schema:Node:start -->
    ...the column table, replaced on every run...
    <!-- schema:Node:end -->

Everything outside those markers is left exactly as found. Rewrite the prose freely;
this script will never touch it.

USAGE
    ./refresh-schema.py            update the tables, keep all prose
    ./refresh-schema.py --check    change nothing, exit 1 if the doc has drifted
    ./refresh-schema.py --rebuild  regenerate the whole section from scratch
                                   (DESTRUCTIVE — throws away the prose; only for
                                   first-time setup)

A new model gets a fresh block appended, with empty prose slots to fill in. A model
that has been deleted is reported but NOT removed, because the writing attached to it
may still be worth keeping or moving.
"""
import argparse
import ast
import json
import re
import subprocess
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parent
REPO = DOCS.parent
MODELS = REPO / "django" / "event_handler" / "models.py"
PAGE = DOCS / "journal" / "database.md"

SECTION_START = "<!-- SCHEMA SECTION START — generated by docs/refresh-schema.py -->"
SECTION_END = "<!-- SCHEMA SECTION END -->"

# Django field class -> what to call it for someone who does not write Django.
TYPE_NAMES = {
    "CharField": "text", "TextField": "long text", "IntegerField": "whole number",
    "PositiveIntegerField": "whole number ≥ 0", "FloatField": "decimal",
    "BooleanField": "true/false", "DateTimeField": "date + time", "DateField": "date",
    "JSONField": "JSON", "ForeignKey": "link →", "OneToOneField": "one-to-one →",
    "ManyToManyField": "many-to-many →", "AutoField": "auto id", "BigAutoField": "auto id",
    "DecimalField": "decimal", "SlugField": "slug", "EmailField": "email",
    "DurationField": "duration", "UUIDField": "uuid",
}


def unparse(node):
    try:
        return ast.unparse(node)
    except Exception:
        return "?"


def read_models():
    """Pull every model, its docstring, its fields and its Meta options out of
    models.py by reading the syntax tree. No Django import, so this runs anywhere."""
    tree = ast.parse(MODELS.read_text())
    models = []
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        if not any("Model" in unparse(b) for b in node.bases):
            continue
        fields, meta = [], []
        for item in node.body:
            if isinstance(item, ast.Assign) and isinstance(item.value, ast.Call):
                call = unparse(item.value.func)
                if "models." not in call:
                    continue
                target = item.targets[0]
                fields.append({
                    "name": target.id if isinstance(target, ast.Name) else "?",
                    "type": call.split(".")[-1],
                    "args": [unparse(a) for a in item.value.args],
                    "kw": {k.arg: unparse(k.value) for k in item.value.keywords if k.arg},
                })
            if isinstance(item, ast.ClassDef) and item.name == "Meta":
                for m in item.body:
                    if isinstance(m, ast.Assign):
                        meta.append(f"{m.targets[0].id} = {unparse(m.value)}")
        models.append({
            "name": node.name,
            "doc": " ".join((ast.get_docstring(node) or "").split()),
            "fields": fields,
            "meta": meta,
        })
    return models


def notes_for(field):
    """The human-readable constraints column."""
    out, kw, args = [], field["kw"], field["args"]
    if field["type"] in ("ForeignKey", "OneToOneField", "ManyToManyField") and args:
        out.append(f"→ `{args[0].strip(chr(39))}`")
    if kw.get("on_delete"):
        out.append(f"on delete: `{kw['on_delete'].replace('models.', '')}`")
    if kw.get("unique") == "True":
        out.append("**unique**")
    if kw.get("null") == "True":
        out.append("optional")
    if kw.get("max_length"):
        out.append(f"max {kw['max_length']}")
    if kw.get("choices"):
        out.append(f"choices: `{kw['choices']}`")
    if kw.get("default") is not None:
        out.append(f"default `{kw['default']}`")
    if kw.get("auto_now_add") == "True":
        out.append("set on create")
    if kw.get("auto_now") == "True":
        out.append("set on save")
    if kw.get("related_name"):
        out.append(f"reverse: `{kw['related_name'].strip(chr(39))}`")
    return ", ".join(out) or "—"


def generated_body(model):
    """The part between the markers — column table plus any Meta rules.
    This is the ONLY thing a refresh overwrites."""
    lines = ["| Column | Type | Notes |", "|---|---|---|"]
    for f in model["fields"]:
        lines.append(f"| `{f['name']}` | {TYPE_NAMES.get(f['type'], f['type'])} | {notes_for(f)} |")
    if model["meta"]:
        lines += ["", "**Table rules**", ""]
        lines += [f"- `{m}`" for m in model["meta"]]
    return "\n".join(lines)


def full_block(model):
    """A complete dropdown for a table nobody has written about yet."""
    summary = model["doc"].split(". ")[0].rstrip(".") if model["doc"] else ""
    head = f":::::{{dropdown}} `{model['name']}`" + (f" — {summary}" if summary else "")
    what = f"**What it is.** {model['doc']}\n\n" if model["doc"] else ""
    return (
        f"{head}\n\n{what}"
        f"<!-- schema:{model['name']}:start -->\n"
        f"{generated_body(model)}\n"
        f"<!-- schema:{model['name']}:end -->\n\n"
        "**Why it exists.** <!-- your summary -->\n\n"
        "**Decisions.** <!-- what was chosen here, and what was rejected -->\n\n"
        ":::::\n"
    )


def section_header():
    return f"""{SECTION_START}

## Table-by-table schema

Every table in the database, generated from `models.py` so it stays honest. Each one is
collapsed — open the tables you care about and leave the rest shut.

:::{{note}}
`id` is not listed. Every table has one — an automatic whole number, assigned by the
database, unique forever. You never set it yourself.

The column tables here are generated. Anything you write around them is preserved —
see `docs/refresh-schema.py`.
:::
"""


def build_section(models):
    return section_header() + "\n" + "\n".join(full_block(m) for m in models) + f"\n{SECTION_END}\n"


def refresh(text, models):
    """Replace each table's generated body in place. Returns (new_text, report)."""
    added, updated, orphaned = [], [], []
    known = {m["name"] for m in models}

    for m in models:
        pattern = re.compile(
            rf"(<!-- schema:{re.escape(m['name'])}:start -->\n).*?(\n<!-- schema:{re.escape(m['name'])}:end -->)",
            re.S,
        )
        if pattern.search(text):
            new = pattern.sub(lambda mo: mo.group(1) + generated_body(m) + mo.group(2), text)
            if new != text:
                updated.append(m["name"])
            text = new
        else:
            # a model with no block yet — append it just before the section end
            block = "\n" + full_block(m)
            if SECTION_END in text:
                text = text.replace(SECTION_END, block + SECTION_END)
            else:
                text = text.rstrip() + "\n" + block
            added.append(m["name"])

    for name in re.findall(r"<!-- schema:(\w+):start -->", text):
        if name not in known:
            orphaned.append(name)

    return text, {"added": added, "updated": updated, "orphaned": orphaned}


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="change nothing; exit 1 if the doc no longer matches models.py")
    ap.add_argument("--rebuild", action="store_true",
                    help="regenerate the whole section, DISCARDING all prose")
    args = ap.parse_args()

    if not MODELS.exists():
        sys.exit(f"models.py not found at {MODELS}")
    models = read_models()
    text = PAGE.read_text()

    if args.rebuild:
        if SECTION_START in text and SECTION_END in text:
            head = text.split(SECTION_START)[0]
            tail = text.split(SECTION_END, 1)[1]
        else:
            head, tail = text.rstrip() + "\n\n---\n\n", "\n"
        new = head + build_section(models) + tail
        PAGE.write_text(new)
        print(f"rebuilt {len(models)} tables (prose discarded)")
        return

    if SECTION_START not in text:
        sys.exit("No schema section found. Run with --rebuild once to create it.")

    new, report = refresh(text, models)

    if args.check:
        if new != text:
            print("Schema docs are out of date. Run: ./docs/refresh-schema.py")
            for k in ("added", "updated"):
                if report[k]:
                    print(f"  {k}: {', '.join(report[k])}")
            sys.exit(1)
        print(f"schema docs up to date ({len(models)} tables)")
        return

    if new != text:
        PAGE.write_text(new)

    total = len(report["added"]) + len(report["updated"])
    if total == 0:
        print(f"no schema changes ({len(models)} tables)")
    else:
        if report["added"]:
            print(f"NEW tables documented (fill in the prose): {', '.join(report['added'])}")
        if report["updated"]:
            print(f"columns refreshed: {', '.join(report['updated'])}")
    if report["orphaned"]:
        print(f"⚠ in the docs but no longer in models.py: {', '.join(report['orphaned'])}")
        print("  left in place on purpose — the writing attached to them may still be worth keeping")


if __name__ == "__main__":
    main()
