#!/usr/bin/env python3
"""Keep the route list in the docs matching urls.py.

The sibling of refresh-schema.py, and it works the same way. journal/apis.md lists
every endpoint the server has. That list has to come from the code, or the first
route somebody adds goes undocumented and the page slowly becomes fiction.

WHAT IS GENERATED vs WHAT IS YOURS
Only the facts table — methods, access level, handler — sits between the markers and
gets replaced on every run:

    <!-- route:racks-register:start -->
    | Methods | POST | ...
    <!-- route:racks-register:end -->

Everything else is preserved: the one-line summary under the heading, the longer
description, and any `####` decisions you attach to a route. Rewrite all of it freely.

USAGE
    ./refresh-routes.py            update the facts, keep all prose
    ./refresh-routes.py --check    change nothing, exit 1 if the page has drifted
    ./refresh-routes.py --rebuild  regenerate the whole section from scratch
                                   (DESTRUCTIVE — discards prose; first-time setup only)

A new route is added under the group its path belongs to, or under "Unsorted" if the
path matches no group. A route that has been deleted is reported but NOT removed —
whatever was written about it may still be worth reading or moving.
"""
import argparse
import ast
import re
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parent
REPO = DOCS.parent
APP = REPO / "django" / "event_handler"
URLS = APP / "urls.py"
VIEW_MODULES = ["views.py", "health.py", "system_status.py", "wifi_config.py"]
PAGE = DOCS / "journal" / "apis.md"

SECTION_START = "<!-- ROUTES SECTION START — generated by docs/refresh-routes.py -->"
SECTION_END = "<!-- ROUTES SECTION END -->"

# Which group each route falls into, matched on the start of its path. Order matters:
# the first prefix that matches wins, and it is also the order groups appear.
#
# ⚠️ ADD NEW PREFIXES HERE. A route matching nothing still gets documented — it lands
# under "Unsorted" — but it belongs in a real group.
GROUPS = [
    ("System",
     "Health, and the settings an operator changes before a real gym uses the box.",
     ("health/", "system/")),
    ("The room",
     "Rack screens, and the sensors on them.",
     ("racks/", "nodes/")),
    ("People",
     "Athletes, the groups they train in, and the staff who run those groups.",
     ("athletes/", "training-groups/")),
    ("The movement catalog",
     "The shared vocabulary plans are written in.",
     ("exercises", "block-categories")),
    ("Templates",
     "Reusable training a coach designs once.",
     ("training-blocks/",)),
    ("Programs and the calendar",
     "A template placed in time, and the slots it generates.",
     ("training-programs/", "scheduled-sessions")),
    ("Running a training day",
     "The live session, and the room's current picture.",
     ("sessions/", "sessions", "room-state")),
    ("Performed work",
     "Sets, reps, prescriptions, maxes, and everything derived from them.",
     ("sets/", "prescriptions", "reference-maxes", "analytics/", "reports/")),
    ("Spreadsheet import",
     "Two routes for all three kinds of sheet.",
     ("imports/",)),
]
UNSORTED = "Unsorted"


def slug(path):
    """A marker-safe key for a route path. `racks/<int:n>/checkin/` -> racks-n-checkin"""
    s = re.sub(r"<[^:>]*:?([^>]*)>", r"\1", path)      # drop the converter, keep the name
    s = re.sub(r"[^a-zA-Z0-9]+", "-", s).strip("-")
    return s or "root"


def read_routes():
    """Every route in urls.py, joined to the view that handles it."""
    views = {}
    for mod in VIEW_MODULES:
        f = APP / mod
        if not f.exists():
            continue
        for node in ast.parse(f.read_text()).body:
            if not isinstance(node, ast.FunctionDef):
                continue
            methods, perm = None, ""
            for d in node.decorator_list:
                s = ast.unparse(d)
                if s.startswith("api_view"):
                    methods = ",".join(re.findall(r"'(\w+)'", s))
                if s.startswith("permission_classes"):
                    perm = s
            if methods:
                views[node.name] = {
                    "methods": methods,
                    "coach": "IsCoach" in perm,
                    "doc": " ".join((ast.get_docstring(node) or "").split()),
                }

    routes = []
    for m in re.finditer(r"path\(\s*'([^']*)'\s*,\s*(?:(\w+)\.)?(\w+)\s*,", URLS.read_text()):
        path, _, fn = m.groups()
        if fn in views:
            routes.append({"path": path, "fn": fn, "slug": slug(path), **views[fn]})
    return routes


def group_of(path):
    for i, (title, _, prefixes) in enumerate(GROUPS):
        if any(path.startswith(p) for p in prefixes):
            return i, title
    return len(GROUPS), UNSORTED


def generated_body(route):
    """The facts table — the ONLY thing a refresh overwrites."""
    access = "🔒 coach only" if route["coach"] else "open — no login"
    return ("| | |\n|---|---|\n"
            f"| **Methods** | `{route['methods']}` |\n"
            f"| **Access** | {access} |\n"
            f"| **Handler** | `{route['fn']}` |")


def full_block(route):
    """A complete entry for a route nobody has written about yet."""
    summary = route["doc"].split(". ")[0].rstrip(".") if route["doc"] else "No description yet"
    longer = ""
    if route["doc"] and len(route["doc"]) > len(summary) + 2:
        longer = f"\n{route['doc']}\n"
    return (
        f"### `/api/{route['path']}`\n\n"
        f"{summary}.\n\n"
        ":::::{dropdown} Detail\n\n"
        f"<!-- route:{route['slug']}:start -->\n"
        f"{generated_body(route)}\n"
        f"<!-- route:{route['slug']}:end -->\n"
        f"{longer}\n"
        ":::::\n"
    )


def section_header():
    return f"""{SECTION_START}

<!-- Groups below are ## so this document keeps a single H1. -->

Every route the server has, grouped by what it touches. The summary is visible; the
detail is one click away. Generated from `urls.py` and the permission decorators, so
it matches what is actually wired up.
"""


def build_section(routes):
    by_slug = {r["slug"]: r for r in routes}
    out = [section_header()]
    for i, (title, blurb, _) in enumerate(GROUPS):
        rs = [r for r in routes if group_of(r["path"])[0] == i]
        if not rs:
            continue
        out.append(f"\n## {title}\n\n{blurb}\n")
        for r in rs:
            out.append("\n" + full_block(r))
    leftover = [r for r in routes if group_of(r["path"])[1] == UNSORTED]
    if leftover:
        out.append(f"\n## {UNSORTED}\n\nNot filed into a group yet. Add a prefix to "
                   "`GROUPS` in `docs/refresh-routes.py`.\n")
        for r in leftover:
            out.append("\n" + full_block(r))
    out.append(f"\n{SECTION_END}\n")
    return "".join(out)


def refresh(text, routes):
    added, updated, orphaned = [], [], []
    known = {r["slug"] for r in routes}

    for r in routes:
        pat = re.compile(
            rf"(<!-- route:{re.escape(r['slug'])}:start -->\n).*?(\n<!-- route:{re.escape(r['slug'])}:end -->)",
            re.S)
        if pat.search(text):
            new = pat.sub(lambda mo: mo.group(1) + generated_body(r) + mo.group(2), text)
            if new != text:
                updated.append(r["path"])
            text = new
        else:
            block = "\n" + full_block(r)
            _, title = group_of(r["path"])
            heading = f"\n## {title}\n"
            if heading in text:
                start = text.index(heading) + len(heading)
                nxt = text.find("\n## ", start)
                cut = nxt if nxt != -1 else text.index(SECTION_END)
                text = text[:cut] + block + text[cut:]
            elif title == UNSORTED:
                text = text.replace(
                    SECTION_END,
                    f"\n## {UNSORTED}\n\nNot filed into a group yet. Add a prefix to "
                    f"`GROUPS` in `docs/refresh-routes.py`.\n{block}" + SECTION_END)
            else:
                text = text.replace(SECTION_END, block + SECTION_END)
            added.append(r["path"])

    for s in re.findall(r"<!-- route:([\w-]+):start -->", text):
        if s not in known:
            orphaned.append(s)
    return text, {"added": added, "updated": updated, "orphaned": orphaned}


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="change nothing; exit 1 if the page no longer matches urls.py")
    ap.add_argument("--rebuild", action="store_true",
                    help="regenerate the whole section, DISCARDING all prose")
    args = ap.parse_args()

    if not URLS.exists():
        sys.exit(f"urls.py not found at {URLS}")
    routes = read_routes()
    text = PAGE.read_text()

    if args.rebuild:
        if SECTION_START in text and SECTION_END in text:
            head = text.split(SECTION_START)[0]
            tail = text.split(SECTION_END, 1)[1]
        else:
            head, tail = text.rstrip() + "\n\n", "\n"
        PAGE.write_text(head + build_section(routes) + tail)
        print(f"rebuilt {len(routes)} routes (prose discarded)")
        return

    if SECTION_START not in text:
        sys.exit("No routes section found. Run with --rebuild once to create it.")

    new, report = refresh(text, routes)

    if args.check:
        if new != text:
            print("Route docs are out of date. Run: ./docs/refresh-routes.py")
            for k in ("added", "updated"):
                if report[k]:
                    print(f"  {k}: {', '.join(report[k])}")
            sys.exit(1)
        print(f"route docs up to date ({len(routes)} routes)")
        return

    if new != text:
        PAGE.write_text(new)

    if not report["added"] and not report["updated"]:
        print(f"no route changes ({len(routes)} routes)")
    else:
        if report["added"]:
            print(f"NEW routes documented (fill in the prose): {', '.join(report['added'])}")
        if report["updated"]:
            print(f"details refreshed: {', '.join(report['updated'])}")
    if report["orphaned"]:
        print(f"⚠ in the docs but no longer in urls.py: {', '.join(report['orphaned'])}")
        print("  left in place on purpose — the writing attached to them may still be useful")


if __name__ == "__main__":
    main()
